// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_T5MC96KeR",
    "aws_user_pools_web_client_id": "6g4i59evtl8pqimam7o4osv68"
};


export default awsmobile;
