// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile =  {
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_4gNKaizoj",
    "aws_user_pools_web_client_id": "7f49lc9at1ake93t1v660549nj"
};


export default awsmobile;
